/*
** SCHEMA: dr
**
*/

--CREATE SCHEMA dr
CREATE SCHEMA IF NOT EXISTS dr AUTHORIZATION dbo;

-- Comment
COMMENT ON SCHEMA dr
    IS 'Contains all the objects needed to operate the dr application';

-- GRANT the privelages needed
GRANT USAGE ON SCHEMA dr TO dr_role;

-- Setup Default Privelages for application user as a catch all
ALTER DEFAULT PRIVILEGES FOR USER dbo IN SCHEMA dr GRANT SELECT ON TABLES TO dr_role;
ALTER DEFAULT PRIVILEGES FOR USER dbo IN SCHEMA dr GRANT INSERT ON TABLES TO dr_role;
ALTER DEFAULT PRIVILEGES FOR USER dbo IN SCHEMA dr GRANT UPDATE ON TABLES TO dr_role;
ALTER DEFAULT PRIVILEGES FOR USER dbo IN SCHEMA dr GRANT DELETE ON TABLES TO dr_role;
ALTER DEFAULT PRIVILEGES FOR USER dbo IN SCHEMA dr GRANT EXECUTE ON FUNCTIONS TO dr_role;
ALTER DEFAULT PRIVILEGES FOR USER dbo IN SCHEMA dr GRANT USAGE ON SEQUENCES TO dr_role;
ALTER DEFAULT PRIVILEGES FOR USER dbo IN SCHEMA dr GRANT SELECT ON SEQUENCES TO dr_role;
ALTER DEFAULT PRIVILEGES FOR USER dbo IN SCHEMA dr GRANT UPDATE ON SEQUENCES TO dr_role;
ALTER DEFAULT PRIVILEGES FOR USER dbo IN SCHEMA dr GRANT USAGE ON TYPES TO dr_role;
ALTER DEFAULT PRIVILEGES FOR USER dbo IN SCHEMA dr GRANT REFERENCES ON TABLES TO dr_role;
ALTER DEFAULT PRIVILEGES FOR USER dbo IN SCHEMA dr GRANT TRIGGER ON TABLES TO dr_role;
