name: Build & Release
on:
  pull_request:
  push:
    tags:
        - v*
jobs:
  create_release:
    if: contains(github.ref, '/tags/v')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8' ]
    steps:
        - uses: actions/checkout@v2
        - name: Get tag version
          id: tag_name
          run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
        - name: Get repo name
          id: repo_name
          run: echo ::set-output name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | sed -e "s/:refs//")
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Build a release
          run: |
            bash bin/build_release_package.sh
          env:
            bamboo_SECRET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            bamboo_ORCA_VERSION: ${{ steps.tag_name.outputs.SOURCE_TAG }}
            bamboo_RELEASE_FLAG: true
